### ISSUE TITLE
use vite@5.2.11 Local development is fine, build error reported

### ISSUE THREAD

**Issue by hengshanMWC** [immutable/ts-immutable-sdk#1764]
use vite@5.2.11 Local development is fine, build error reported
<img width="373" alt="image" src="https://github.com/immutable/ts-immutable-sdk/assets/45714422/89adb5b6-884c-480a-975d-373ad0a08a84">
<img width="450" alt="image" src="https://github.com/immutable/ts-immutable-sdk/assets/45714422/d6a6a542-676b-46ac-9033-6f0d6a51861a">
<img width="841" alt="image" src="https://github.com/immutable/ts-immutable-sdk/assets/45714422/d8993597-10e7-430f-8b45-55b91f48380b">

**Comment by hengshanMWC** [comment]
[issues](https://github.com/Uniswap/sdks/issues/23)

**Comment by wdinau** [comment]
hey @hengshanMWC
I installed a vanilla react app and using vite@5.2.11.
my dependency and index both had @imtbl/sdk v1.36.0

I have no problem running `npm run dev` and `npm run build`
don't see error in server console log or the frontend console log

Could you please give me more information on exactly what did you do seeing that error from which console?

**Comment by wdinau** [comment]
close issue due to inactivity.
